### ISSUE TITLE
[lsi] -h(ヘルプ)の時の--num-lenの表示が変

### ISSUE THREAD

**Issue by oba18** [ShotaroKataoka/ls-Improved#44]
![image](https://user-images.githubusercontent.com/33748835/85936351-bd161380-b934-11ea-9e4e-5b2da92fa7c5.png)

**Comment by oba18** [comment]
ヘルプメッセージ適当につけた感あるから，ちゃんと考えないとなってのもある

**Comment by ShotaroKataoka** [comment]
表示とは？

**Comment by oba18** [comment]
`-n`と`-s`だけ
`-s SEARCH, --search SEARCH`
`-n NUM_LEN. --num-len NUM_LEM`
になってない？

これってこういう仕様なんだっけ？

**Comment by ShotaroKataoka** [comment]
あー、たぶん
`-s kldsjflsjfl`
みたいにうつってことを表してる。

**Comment by oba18** [comment]
なるほど
そういうことか，なら問題ないのか

**Comment by ShotaroKataoka** [comment]
確かにSEARCHだと分かりづらいから変えよう
パラメータでかえれたはず

**Comment by ShotaroKataoka** [comment]
ISSUE立て直す？

**Comment by oba18** [comment]
立て直しましょう！荒らして申し訳ない！
