### ISSUE TITLE
[lsi] descriptionでマークダウンに対応する

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/ls-Improved#63]

**Comment by conao3** [comment]
こんにちは。
Qiitaの記事を見て来ました。

マークダウンに対応する予定があるとのことですが、マークダウンに対応するよりもANSIのエスケープコードに対応して頂ければとても嬉しいです。
[ANSIエスケープコード](https://www.mm2d.net/main/prog/c/console-02.html)

今の形式はls-Improved独自の形式ですが、ANSIのエスケープコードは標準化されており、様々なツールと協調できるようになります。
ご検討頂ければと思います。

**Comment by ShotaroKataoka** [comment]
@conao3 さん

おっしゃる通り、標準的なエスケープコードに対応するべきでした……
もともと内内のツールだったせいで適当をやってしまいました。
こちらできるだけ早く対応しようと思います。

ご意見ありがとうございました。
今後ともご指導ご鞭撻のほどよろしくお願いいたします。

**Comment by ShotaroKataoka** [comment]
syntaxはありかも？
実装しないという方向で
