### ISSUE TITLE
[mkdiri] ファイルへのメモの追加

### ISSUE THREAD

**Issue by conao3** [ShotaroKataoka/ls-Improved#64]
現在.description.lsiに保存されている文字列をそのフォルダのメモとして表示していますが、
その都合上、ファイルへのメモの追加ができません。

`lsi`はファイルだけの一覧表示ができますが、説明欄が「File」とだけ表示され、少し寂しい感じがあります。
`.description.lsi` をどうにか終端させ、それ以降はファイルへのメモということにできないでしょうか。
```
folder memo

---
/model-0.tar/score=0.85, lr=1e-6, batch_size=16
/model-1.tar/score=0.90, lr=1e-3, batch_size=16
/model-4.tar/score=0.95, lr=1e-6, batch_size=16 +BatchNorm
best validation result
/model-5.tar/score=0.93, lr=1e-6, batch_size=32 +BatchNorm
/model-5 old.tar/score=0.92, lr=1e-5, batch_size=32 +BatchNorm
```
(/がファイルの名前の一部になることはありません。
/区切りのデータとして認識し、行頭の/が来るまでを説明文とすれば複数行の説明文も書けると思います。)

しかし、この方法だと。`---`が説明文で使用できなくなりますし、`mkdiri -a`でファイルのメモが全部消えてしまいます。
そのため、別途`.description-files.lsi`を作り、
```
/model-0.tar/score=0.85, lr=1e-6, batch_size=16
/model-1.tar/score=0.90, lr=1e-3, batch_size=16
/model-4.tar/score=0.95, lr=1e-6, batch_size=16 +BatchNorm
best validation result
/model-5.tar/score=0.93, lr=1e-6, batch_size=32 +BatchNorm
/model-5 old.tar/score=0.92, lr=1e-5, batch_size=32 +BatchNorm
```
というファイルを利用する方法はどうでしょうか。
ご検討よろしくお願いします。

**Comment by ShotaroKataoka** [comment]
@conao3 
ありがとうございます！
これまで身内のツールとして使っていたせいで、どの機能に需要があるかがいまいちわからなかったのでご意見いただき非常にありがたいです！
こちらの機能の実装を前向きに検討します。（おそらくANSIの対応のアップデート後に実装すると思います）

１つお伺いしたいことがあります。
ファイルを移動・削除・リネームしたさいに説明文パスとの整合性が取れなくなります。同期させる実装の難度が少し高いので、ひとまずファイルの変更に対してはユーザ側で対応するような形でも大丈夫でしょうか？（同期できれば一番良いのですが。。。）

こちらアドバイスいただけると非常に助かります。
よろしくお願いいたします。

**Comment by conao3** [comment]
あ、それは難しいので、無視でいいと思います。
それか、`mkdiri`に対応する`mvi`のようなコマンドを用意してmvと説明文の更新を同時にするコマンドを提供しても良いかもしれません。
しかし、`mkdiri`はまだしも、`mvi`は`mv -i`でエイリアスしてる人もいると思うのでグローバルに公開するのは少し抵抗があるかもしれません。。 [mvi - Google search](https://www.google.com/search?q=%22mvi%22+bash+alias)
公開するなら`lsi-mv`とかでしょうか。。？

**Comment by ShotaroKataoka** [comment]
そうですね
ファイルの移動などに対応するときは専用のコマンドを作ることになりそうです。

ひとまずはファイルへのコメント付けへの対応を行い、需要がありそうならファイルの管理についても対応していこうと思います。
ありがとうございます！

**Comment by ShotaroKataoka** [comment]
developブランチで対応済み
v0.5.0で実装予定
